CFLAGS=-g
#CFLAGS=-g.
CC=gcc

xpadtest: gpio_2016_04_11_working_without_gpio_pins.c gpio_2016_04_11_working_without_gpio_pins.o
	${CC} ${CFLAGS} -o gpio_2016_04_11_working_without_gpio_pins gpio_2016_04_11_working_without_gpio_pins.o -lwiringPi

